# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82d131374a70e970a6ed71296c176f19950b82466cba43fac0cdb7e11fc1a0d6ed2928f76cd0d598f11c373c02e04ff561ebb8c341e0b61c17e9bcf2db9d42d9

test:
  secret_key_base: d2ecca74c220b6fcb1ae9f370ac0db89eadca837e148390906cd88f67fd68dc68fe862f491dfd38a06a9c936805e85675000a4e1867eaf3b973145465295e840

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
